---
version: "3.3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka_network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Enable auto-creation of topics
    networks:
      - kafka_network

  notification-service:
    image: justtheword/notification-service:${NOTIFICATION_SERVICE_TAG}
    container_name: notification-service
    hostname: notification-service
    depends_on:
      - broker
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
    ports:
      - "8090:8090"
    networks:
      - kafka_network

  simple-jira-app:
    image: justtheword/simple-jira-app:${SIMPLE_JIRA_APP_TAG}
    container_name: simple-jira-app
    hostname: simple-jira-app
    depends_on:
      - broker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://OURPOSTGREINSTANCE:5432/simple_jira
      SPRING_DATASOURCE_USERNAME: simple_jira_admin
      SPRING_DATASOURCE_PASSWORD: NOBODYKNOWSTHISSECRET
      HAZELCAST_NETWORK_JOIN_TCPIP_MEMBERS: broker
    ports:
      - "8080:8080"
    networks:
      - kafka_network

  frontend:
    image: justtheword/frontend:${FRONTEND_TAG}
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
